import type { AnalysisResult } from "@/types/analysis";

/**
 * Converts an AnalysisResult into a readable Markdown document.
 */
export function formatAnalysisAsMarkdown(result: AnalysisResult): string {
  const lines: string[] = [];

  lines.push("# NewsLens AI — Analysis Report");
  lines.push("");

  lines.push("## Summary");
  result.summary.forEach((point) => lines.push(`- ${point}`));
  lines.push("");

  lines.push("## Tone Analysis");
  lines.push(`**Score:** ${result.toneScore} / 100`);
  lines.push("");
  lines.push(result.toneExplanation);
  lines.push("");

  if (result.emotionalWords.length > 0) {
    lines.push("## Emotional Language");
    lines.push(result.emotionalWords.map((w) => `\`${w}\``).join(", "));
    lines.push("");
  }

  lines.push("## Key Claims");
  result.claims.forEach((claim) => lines.push(`- ${claim.text}`));
  lines.push("");

  lines.push("## Questions to Ask");
  result.questions.forEach((q) => lines.push(`- ${q}`));
  lines.push("");

  lines.push("## Credibility Indicators");
  lines.push(`- Named Sources: ${result.credibility.namedSources ? "Yes" : "No"}`);
  lines.push(`- Anonymous Sources: ${result.credibility.anonymousSources ? "Yes" : "No"}`);
  lines.push(`- Statistics Present: ${result.credibility.statisticsPresent ? "Yes" : "No"}`);
  lines.push(`- Citations Present: ${result.credibility.citationsPresent ? "Yes" : "No"}`);
  lines.push("");

  if (result.keywords.length > 0) {
    lines.push("## Related Topics");
    lines.push(result.keywords.join(", "));
    lines.push("");
  }

  if (result.timeline.length > 0) {
    lines.push("## Timeline");
    result.timeline.forEach((event) => lines.push(`- **${event.date}:** ${event.event}`));
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by NewsLens AI*");

  return lines.join("\n");
}